name: exebition
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  wakelock: ^0.6.2
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  file_picker: ^5.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.13.1"


flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
